services:
  easysave-logserver:
    build:
      context: ..          # src/ (remonte d'un niveau depuis LogServer/)
      dockerfile: EasySave.LogServer/Dockerfile
    container_name: easysave-logserver
    ports:
      - "11000:11000"
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped